name: licenses
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install google/addlincense
        uses: jaxxstorm/action-install-gh-release@25d5e2dd555cd74f1fab9ac1e6ea117acde2c0c4 #v1.12.0
        with:
          repo: google/addlincense
          tag: v1.1.1
          cache: enable

      - name: Check license headers
        run: >
          addlicense \
            -check \
            -c "Edge & Node, GraphOps, and Semiotic Labs." \
            -l "apache" \
            -s=only \
            -ignore '.github/**' \
            -ignore '.sqlx/**' \
            -ignore 'migrations/*.sql' \
            .
